export const ingredientsDB = [
  // Viandes & Volailles
  { id: 1,  name: "Blanc de poulet",                       calories: 120, protein: 26,  carbs: 0,   fat: 1.5, unit: "g",  category: "Viandes" },
  { id: 2,  name: "Boeuf haché 5%",                        calories: 160, protein: 21,  carbs: 0,   fat: 5,   unit: "g",  category: "Viandes" },
  { id: 34, name: "Escalope de dinde",                     calories: 104, protein: 24,  carbs: 0,   fat: 1,   unit: "g",  category: "Viandes" },
  { id: 35, name: "Jambon blanc (sans couenne)",           calories: 107, protein: 18,  carbs: 1,   fat: 3.5, unit: "g",  category: "Viandes" },
  { id: 53, name: "Escalope de veau",                      calories: 96,  protein: 20,  carbs: 0,   fat: 1.5, unit: "g",  category: "Viandes" },
  { id: 54, name: "Steak haché 10%",                       calories: 180, protein: 20,  carbs: 0,   fat: 10,  unit: "g",  category: "Viandes" },
  { id: 55, name: "Steak haché 15%",                       calories: 210, protein: 19,  carbs: 0,   fat: 15,  unit: "g",  category: "Viandes" },
  { id: 56, name: "Côte de boeuf",                         calories: 250, protein: 24,  carbs: 0,   fat: 17,  unit: "g",  category: "Viandes" },
  { id: 57, name: "Canard",                                calories: 201, protein: 21,  carbs: 0,   fat: 12,  unit: "g",  category: "Viandes" },

  // Poissons & Fruits de mer
  { id: 3,  name: "Saumon",                                calories: 208, protein: 20,  carbs: 0,   fat: 13,  unit: "g",  category: "Poissons & Mer" },
  { id: 4,  name: "Thon en boîte (au naturel)",           calories: 110, protein: 25,  carbs: 0,   fat: 1,   unit: "g",  category: "Poissons & Mer" },
  { id: 36, name: "Crevettes",                             calories: 99,  protein: 21,  carbs: 0.9, fat: 1.1, unit: "g",  category: "Poissons & Mer" },
  { id: 37, name: "Cabillaud",                             calories: 82,  protein: 18,  carbs: 0,   fat: 0.7, unit: "g",  category: "Poissons & Mer" },
  { id: 38, name: "Sardines en boîte (égouttées)",        calories: 208, protein: 25,  carbs: 0,   fat: 12,  unit: "g",  category: "Poissons & Mer" },
  { id: 58, name: "Truite",                                calories: 148, protein: 21,  carbs: 0,   fat: 7,   unit: "g",  category: "Poissons & Mer" },
  { id: 59, name: "Bar",                                   calories: 82,  protein: 18,  carbs: 0,   fat: 0.9, unit: "g",  category: "Poissons & Mer" },
  { id: 60, name: "Huîtres",                               calories: 68,  protein: 7,   carbs: 4,   fat: 2,   unit: "g",  category: "Poissons & Mer" },
  { id: 61, name: "Moules",                                calories: 88,  protein: 12,  carbs: 3.7, fat: 1.5, unit: "g",  category: "Poissons & Mer" },

  // Œufs & Protéines végétales
  { id: 5,  name: "Œuf entier",                            calories: 155, protein: 13,  carbs: 1.1, fat: 11,  unit: "g",  category: "Œufs & Végétal", countInfo: { singular: "œuf", plural: "œufs", gramsPerUnit: 60 } },
  { id: 6,  name: "Blanc d'œuf",                          calories: 52,  protein: 11,  carbs: 0.7, fat: 0.2, unit: "g",  category: "Œufs & Végétal", countInfo: { singular: "blanc", plural: "blancs", gramsPerUnit: 35 } },
  { id: 62, name: "Œufs de caille",                       calories: 158, protein: 13,  carbs: 0.6, fat: 11,  unit: "g",  category: "Œufs & Végétal", countInfo: { singular: "œuf de caille", plural: "œufs de caille", gramsPerUnit: 9 } },
  { id: 7,  name: "Tofu",                                  calories: 76,  protein: 8,   carbs: 2,   fat: 4,   unit: "g",  category: "Œufs & Végétal" },
  { id: 111, name: "Edamame (cuit)",                       calories: 122, protein: 11,  carbs: 10,  fat: 5,   unit: "g",  category: "Œufs & Végétal" },
  { id: 112, name: "Tempeh",                               calories: 193, protein: 19,  carbs: 9,   fat: 11,  unit: "g",  category: "Œufs & Végétal" },
  { id: 113, name: "Seitan",                               calories: 370, protein: 75,  carbs: 14,  fat: 1.9, unit: "g",  category: "Œufs & Végétal" },

  // Féculents & Céréales
  { id: 8,  name: "Riz basmati (cru)",                    calories: 350, protein: 8,   carbs: 78,  fat: 1,   unit: "g",  category: "Féculents" },
  { id: 40, name: "Riz complet (cru)",                     calories: 362, protein: 8,   carbs: 76,  fat: 2.7, unit: "g",  category: "Féculents" },
  { id: 9,  name: "Pâtes (crues)",                        calories: 360, protein: 12,  carbs: 72,  fat: 1.5, unit: "g",  category: "Féculents" },
  { id: 98, name: "Pâtes complètes (crues)",               calories: 352, protein: 14,  carbs: 68,  fat: 2.4, unit: "g",  category: "Féculents" },
  { id: 10, name: "Flocons d'avoine",                      calories: 370, protein: 13,  carbs: 60,  fat: 7,   unit: "g",  category: "Féculents" },
  { id: 11, name: "Pomme de terre",                        calories: 86,  protein: 2,   carbs: 20,  fat: 0.1, unit: "g",  category: "Féculents" },
  { id: 12, name: "Patate douce",                          calories: 86,  protein: 1.6, carbs: 20,  fat: 0.1, unit: "g",  category: "Féculents" },
  { id: 13, name: "Lentilles (crues)",                     calories: 353, protein: 25,  carbs: 60,  fat: 1,   unit: "g",  category: "Féculents" },
  { id: 14, name: "Quinoa (cru)",                          calories: 368, protein: 14,  carbs: 64,  fat: 6,   unit: "g",  category: "Féculents" },
  { id: 39, name: "Pain complet",                          calories: 247, protein: 9,   carbs: 44,  fat: 3.4, unit: "g",  category: "Féculents" },
  { id: 97, name: "Pain blanc",                            calories: 265, protein: 9,   carbs: 49,  fat: 3,   unit: "g",  category: "Féculents" },
  { id: 41, name: "Pois chiches (cuits)",                  calories: 164, protein: 8.9, carbs: 27,  fat: 2.6, unit: "g",  category: "Féculents" },
  { id: 42, name: "Haricots rouges (cuits)",               calories: 127, protein: 8.7, carbs: 22,  fat: 0.5, unit: "g",  category: "Féculents" },
  { id: 99, name: "Couscous (cru)",                        calories: 376, protein: 13,  carbs: 77,  fat: 0.6, unit: "g",  category: "Féculents" },
  { id: 100, name: "Polenta (crue)",                       calories: 359, protein: 8.7, carbs: 75,  fat: 3,   unit: "g",  category: "Féculents" },
  { id: 118, name: "Crème de riz (crue)",                  calories: 362, protein: 6.5, carbs: 80,  fat: 1,   unit: "g",  category: "Féculents" },
  { id: 119, name: "Galette de riz",                       calories: 385, protein: 7,   carbs: 83,  fat: 2.8, unit: "g",  category: "Féculents", countInfo: { singular: "galette", plural: "galettes", gramsPerUnit: 9 } },
  { id: 120, name: "Tortilla de blé",                      calories: 306, protein: 8.2, carbs: 51,  fat: 7.8, unit: "g",  category: "Féculents", countInfo: { singular: "tortilla", plural: "tortillas", gramsPerUnit: 40 } },
  { id: 121, name: "Farine de blé T55",                    calories: 348, protein: 10,  carbs: 73,  fat: 1.2, unit: "g",  category: "Féculents" },
  { id: 136, name: "Pâte à pizza", calories: 260, protein: 8, carbs: 45, fat: 4, unit: "g", category: "Féculents" },

  // Légumes
  { id: 15, name: "Brocoli",                               calories: 34,  protein: 2.8, carbs: 4,   fat: 0.4, unit: "g",  category: "Légumes" },
  { id: 16, name: "Courgette",                             calories: 17,  protein: 1.2, carbs: 3.1, fat: 0.3, unit: "g",  category: "Légumes" },
  { id: 17, name: "Carotte",                               calories: 41,  protein: 0.9, carbs: 10,  fat: 0.2, unit: "g",  category: "Légumes" },
  { id: 18, name: "Épinards",                              calories: 23,  protein: 2.9, carbs: 3.6, fat: 0.4, unit: "g",  category: "Légumes" },
  { id: 19, name: "Tomate",                                calories: 18,  protein: 0.9, carbs: 3.9, fat: 0.2, unit: "g",  category: "Légumes" },
  { id: 63, name: "Poivron rouge",                         calories: 31,  protein: 1,   carbs: 6,   fat: 0.3, unit: "g",  category: "Légumes" },
  { id: 64, name: "Poivron jaune",                         calories: 30,  protein: 1,   carbs: 5.5, fat: 0.3, unit: "g",  category: "Légumes" },
  { id: 65, name: "Champignon de Paris",                   calories: 22,  protein: 3.1, carbs: 1.3, fat: 0.3, unit: "g",  category: "Légumes" },
  { id: 66, name: "Aubergine",                             calories: 25,  protein: 0.8, carbs: 5,   fat: 0.2, unit: "g",  category: "Légumes" },
  { id: 67, name: "Oignon",                                calories: 40,  protein: 1.1, carbs: 9,   fat: 0.1, unit: "g",  category: "Légumes" },
  { id: 68, name: "Ail",                                   calories: 149, protein: 6.4, carbs: 33,  fat: 0.5, unit: "g",  category: "Légumes" },
  { id: 69, name: "Chou-fleur",                            calories: 25,  protein: 1.9, carbs: 5,   fat: 0.3, unit: "g",  category: "Légumes" },
  { id: 70, name: "Haricots verts",                        calories: 30,  protein: 2,   carbs: 6.4, fat: 0.2, unit: "g",  category: "Légumes" },
  { id: 71, name: "Laitue",                                calories: 15,  protein: 1.2, carbs: 2.9, fat: 0.2, unit: "g",  category: "Légumes" },
  { id: 72, name: "Betterave",                             calories: 43,  protein: 1.6, carbs: 8,   fat: 0.2, unit: "g",  category: "Légumes" },
  { id: 73, name: "Courge butternut",                      calories: 45,  protein: 1,   carbs: 11,  fat: 0.1, unit: "g",  category: "Légumes" },
  { id: 122, name: "Concombre",                            calories: 15,  protein: 0.6, carbs: 3.6, fat: 0.1, unit: "g",  category: "Légumes" },
  { id: 123, name: "Maïs (cuit)",                          calories: 108, protein: 3.4, carbs: 23,  fat: 1.2, unit: "g",  category: "Légumes" },
  { id: 124, name: "Poireau",                              calories: 31,  protein: 1.5, carbs: 7.3, fat: 0.3, unit: "g",  category: "Légumes" },
  { id: 125, name: "Céleri branche",                       calories: 14,  protein: 0.7, carbs: 2.9, fat: 0.1, unit: "g",  category: "Légumes" },
  { id: 126, name: "Petit pois (cuit)",                    calories: 84,  protein: 5.4, carbs: 14,  fat: 0.4, unit: "g",  category: "Légumes" },
  { id: 127, name: "Artichaut",                            calories: 47,  protein: 3.3, carbs: 10,  fat: 0.2, unit: "g",  category: "Légumes" },

  // Fruits
  { id: 20, name: "Banane",                                calories: 89,  protein: 1.1, carbs: 23,  fat: 0.3, unit: "g",  category: "Fruits", countInfo: { singular: "banane", plural: "bananes", gramsPerUnit: 120 } },
  { id: 21, name: "Pomme",                                 calories: 52,  protein: 0.3, carbs: 14,  fat: 0.2, unit: "g",  category: "Fruits", countInfo: { singular: "pomme", plural: "pommes", gramsPerUnit: 180 } },
  { id: 22, name: "Fraise",                                calories: 32,  protein: 0.7, carbs: 7.7, fat: 0.3, unit: "g",  category: "Fruits" },
  { id: 23, name: "Avocat",                                calories: 160, protein: 2,   carbs: 8.5, fat: 15,  unit: "g",  category: "Fruits", countInfo: { singular: "avocat", plural: "avocats", gramsPerUnit: 160 } },
  { id: 74, name: "Orange",                                calories: 47,  protein: 0.9, carbs: 11,  fat: 0.1, unit: "g",  category: "Fruits", countInfo: { singular: "orange", plural: "oranges", gramsPerUnit: 150 } },
  { id: 75, name: "Kiwi",                                  calories: 61,  protein: 1.1, carbs: 14,  fat: 0.5, unit: "g",  category: "Fruits", countInfo: { singular: "kiwi", plural: "kiwis", gramsPerUnit: 80 } },
  { id: 76, name: "Raisin",                                calories: 67,  protein: 0.6, carbs: 17,  fat: 0.2, unit: "g",  category: "Fruits" },
  { id: 78, name: "Cerise",                                calories: 63,  protein: 1.1, carbs: 15,  fat: 0.3, unit: "g",  category: "Fruits" },
  { id: 79, name: "Pêche",                                 calories: 39,  protein: 0.9, carbs: 10,  fat: 0.2, unit: "g",  category: "Fruits", countInfo: { singular: "pêche", plural: "pêches", gramsPerUnit: 150 } },
  { id: 80, name: "Abricot",                               calories: 48,  protein: 1.4, carbs: 11,  fat: 0.4, unit: "g",  category: "Fruits", countInfo: { singular: "abricot", plural: "abricots", gramsPerUnit: 50 } },
  { id: 81, name: "Melon cantaloup",                       calories: 34,  protein: 0.8, carbs: 8,   fat: 0.2, unit: "g",  category: "Fruits" },
  { id: 82, name: "Myrtille",                              calories: 57,  protein: 0.7, carbs: 14,  fat: 0.3, unit: "g",  category: "Fruits" },
  { id: 83, name: "Raisin sec",                            calories: 299, protein: 3.1, carbs: 79,  fat: 0.3, unit: "g",  category: "Fruits" },
  { id: 131, name: "Dattes (séchées)",                     calories: 277, protein: 1.8, carbs: 75,  fat: 0.2, unit: "g",  category: "Fruits" },

  // Produits laitiers
  { id: 24, name: "Lait demi-écrémé",                      calories: 46,  protein: 3.3, carbs: 4.8, fat: 1.5, unit: "ml", category: "Laitiers" },
  { id: 84, name: "Lait entier",                           calories: 61,  protein: 3.2, carbs: 4.8, fat: 3.3, unit: "ml", category: "Laitiers" },
  { id: 28, name: "Crème liquide 30%",                     calories: 292, protein: 2.1, carbs: 2.8, fat: 30,  unit: "ml", category: "Laitiers" },
  { id: 117, name: "Crème fraîche épaisse",                calories: 215, protein: 2.5, carbs: 2.9, fat: 21,  unit: "g",  category: "Laitiers" },
  { id: 31, name: "Fromage blanc 0%",                      calories: 48,  protein: 8,   carbs: 4,   fat: 0,   unit: "g",  category: "Laitiers" },
  { id: 32, name: "Skyr",                                  calories: 57,  protein: 10,  carbs: 4,   fat: 0.2, unit: "g",  category: "Laitiers" },
  { id: 43, name: "Yaourt grec nature 0%",                 calories: 56,  protein: 10,  carbs: 3.6, fat: 0.4, unit: "g",  category: "Laitiers" },
  { id: 85, name: "Yaourt nature",                         calories: 59,  protein: 3.5, carbs: 4.7, fat: 0.4, unit: "g",  category: "Laitiers" },
  { id: 44, name: "Cottage cheese",                        calories: 84,  protein: 11,  carbs: 3.4, fat: 3,   unit: "g",  category: "Laitiers" },
  { id: 45, name: "Mozzarella (light)",                    calories: 188, protein: 19,  carbs: 2,   fat: 12,  unit: "g",  category: "Laitiers" },
  { id: 46, name: "Parmesan",                              calories: 392, protein: 36,  carbs: 0,   fat: 26,  unit: "g",  category: "Laitiers" },
  { id: 86, name: "Fromage de chèvre frais",               calories: 245, protein: 17,  carbs: 1.5, fat: 20,  unit: "g",  category: "Laitiers" },
  { id: 87, name: "Emmental",                              calories: 380, protein: 28,  carbs: 0,   fat: 31,  unit: "g",  category: "Laitiers" },
  { id: 88, name: "Brie",                                  calories: 334, protein: 20,  carbs: 0.7, fat: 28,  unit: "g",  category: "Laitiers" },

  // Oléagineux & Graines
  { id: 29, name: "Amandes",                               calories: 579, protein: 21,  carbs: 22,  fat: 50,  unit: "g",  category: "Oléagineux" },
  { id: 30, name: "Beurre de cacahuète",                   calories: 588, protein: 25,  carbs: 20,  fat: 50,  unit: "g",  category: "Oléagineux" },
  { id: 47, name: "Graines de chia",                       calories: 486, protein: 17,  carbs: 42,  fat: 31,  unit: "g",  category: "Oléagineux" },
  { id: 48, name: "Noix de cajou",                         calories: 553, protein: 18,  carbs: 30,  fat: 44,  unit: "g",  category: "Oléagineux" },
  { id: 49, name: "Graines de lin",                        calories: 534, protein: 18,  carbs: 29,  fat: 42,  unit: "g",  category: "Oléagineux" },
  { id: 92, name: "Cacahuètes",                            calories: 567, protein: 26,  carbs: 16,  fat: 49,  unit: "g",  category: "Oléagineux" },
  { id: 93, name: "Noisettes",                             calories: 628, protein: 15,  carbs: 17,  fat: 61,  unit: "g",  category: "Oléagineux" },
  { id: 94, name: "Pistaches",                             calories: 562, protein: 20,  carbs: 28,  fat: 45,  unit: "g",  category: "Oléagineux" },
  { id: 95, name: "Noix",                                  calories: 654, protein: 15,  carbs: 14,  fat: 65,  unit: "g",  category: "Oléagineux" },
  { id: 96, name: "Graines de courge",                     calories: 559, protein: 25,  carbs: 15,  fat: 49,  unit: "g",  category: "Oléagineux" },

  // Boissons
  { id: 25, name: "Lait d'amande (sans sucre)",            calories: 13,  protein: 0.4, carbs: 0.1, fat: 1.1, unit: "ml", category: "Boissons" },
  { id: 26, name: "Jus d'orange",                         calories: 45,  protein: 0.7, carbs: 10,  fat: 0.2, unit: "ml", category: "Boissons" },
  { id: 89, name: "Lait de coco (allégé)",                 calories: 68,  protein: 0.7, carbs: 1,   fat: 7,   unit: "ml", category: "Boissons" },
  { id: 90, name: "Lait d'avoine",                         calories: 45,  protein: 1,   carbs: 4,   fat: 1.5, unit: "ml", category: "Boissons" },
  { id: 91, name: "Lait de soja",                          calories: 33,  protein: 2.7, carbs: 1.9, fat: 1.6, unit: "ml", category: "Boissons" },
  { id: 106, name: "Bouillon de poule",                    calories: 15,  protein: 1.4, carbs: 0.5, fat: 0.5, unit: "ml", category: "Boissons" },
  { id: 133, name: "Café",                                 calories: 2,   protein: 0.1, carbs: 0,   fat: 0,   unit: "ml", category: "Boissons" },
  { id: 134, name: "Thé",                                  calories: 1,   protein: 0,   carbs: 0.1, fat: 0,   unit: "ml", category: "Boissons" },
  { id: 135, name: "Eau de coco",                          calories: 19,  protein: 0.7, carbs: 3.7, fat: 0.2, unit: "ml", category: "Boissons" },

  // Matières grasses
  { id: 27,  name: "Huile d'olive",                        calories: 900, protein: 0,   carbs: 0,   fat: 100, unit: "g",  category: "Matières grasses" },
  { id: 114, name: "Beurre",                               calories: 717, protein: 0.9, carbs: 0.6, fat: 81,  unit: "g",  category: "Matières grasses" },
  { id: 115, name: "Huile de coco",                        calories: 892, protein: 0,   carbs: 0,   fat: 99,  unit: "g",  category: "Matières grasses" },
  { id: 116, name: "Huile de colza",                       calories: 900, protein: 0,   carbs: 0,   fat: 100, unit: "g",  category: "Matières grasses" },

  // Compléments sportifs
  { id: 33,  name: "Whey Protein",                         calories: 380, protein: 80,  carbs: 5,   fat: 4,   unit: "g",  category: "Compléments" },
  { id: 107, name: "Caséine",                              calories: 360, protein: 80,  carbs: 3,   fat: 2,   unit: "g",  category: "Compléments" },
  { id: 108, name: "Whey Isolate",                         calories: 360, protein: 85,  carbs: 2,   fat: 1,   unit: "g",  category: "Compléments" },
  { id: 109, name: "Protéine de pois",                     calories: 360, protein: 80,  carbs: 4,   fat: 3,   unit: "g",  category: "Compléments" },
  { id: 110, name: "Créatine monohydrate",                 calories: 0,   protein: 0,   carbs: 0,   fat: 0,   unit: "g",  category: "Compléments" },

  // Condiments & Sauces
  { id: 50,  name: "Sauce soja (faible sodium)",           calories: 60,  protein: 8,   carbs: 7,   fat: 0,   unit: "ml", category: "Condiments" },
  { id: 51,  name: "Ketchup",                              calories: 112, protein: 1.5, carbs: 26,  fat: 0.1, unit: "g",  category: "Condiments" },
  { id: 52,  name: "Moutarde",                             calories: 66,  protein: 4.4, carbs: 6,   fat: 3.3, unit: "g",  category: "Condiments" },
  { id: 101, name: "Miel",                                 calories: 304, protein: 0.3, carbs: 82,  fat: 0,   unit: "g",  category: "Condiments" },
  { id: 102, name: "Sauce tomate",                         calories: 18,  protein: 0.9, carbs: 3.5, fat: 0.2, unit: "g",  category: "Condiments" },
  { id: 103, name: "Pâte de tomate",                       calories: 82,  protein: 3.8, carbs: 18,  fat: 0.3, unit: "g",  category: "Condiments" },
  { id: 104, name: "Vinaigre blanc",                       calories: 18,  protein: 0,   carbs: 0.4, fat: 0,   unit: "ml", category: "Condiments" },
  { id: 105, name: "Citron frais",                         calories: 29,  protein: 1.1, carbs: 9,   fat: 0.3, unit: "g",  category: "Condiments", countInfo: { singular: "citron", plural: "citrons", gramsPerUnit: 100 } },
  { id: 128, name: "Chocolat noir 70%",                    calories: 546, protein: 8,   carbs: 46,  fat: 36,  unit: "g",  category: "Condiments" },
  { id: 129, name: "Sucre blanc",                          calories: 387, protein: 0,   carbs: 100, fat: 0,   unit: "g",  category: "Condiments" },
  { id: 130, name: "Sirop d'agave",                        calories: 310, protein: 0.1, carbs: 76,  fat: 0,   unit: "g",  category: "Condiments" },
  { id: 132, name: "Confiture (standard)",                 calories: 250, protein: 0.4, carbs: 62,  fat: 0.1, unit: "g",  category: "Condiments" },
];